### ISSUE TITLE
Please add a papar.

### ISSUE THREAD

**Issue by Yiiclass** [52CV/ECCV-2024-Papers#3]
Domain: Low-level Vision
Paper title: Object-Aware NIR-to-Visible Translation
Paper link: https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/03338.pdf
Code link: https://github.com/Yiiclass/Sherry
Dataset: https://1drv.ms/f/c/e976acca7b9fcd1f/EiDybm6th_dCmf7v0HDM-hYBjuHcOsVkjCa2067pgzaUxQ?e=eVisVX

**Comment by 52CV** [comment]
ok
